doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Company:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Company/Model'
                prefix: 'Company\Model'
                alias: Company
