version: '3.5'

services:
  php-fpm:
    container_name: php
    build: ./infrastructure/docker/php-fpm
    depends_on:
      - db
      - db_test
    volumes:
      - ./:/app

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432
    volumes:
      - ./var/docker/db/postgres:/var/lib/postgresql/data

  db_test:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
