name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Run docker compose
        run: docker-compose up -d

      - name: Validate composer.json and composer.lock
        run: docker exec php bash -c "composer validate"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: docker exec php bash -c "composer install --prefer-dist --no-progress"

      - name: Run static code analysis
        run: |
          docker exec php bash -c "bin/ecs check"
          docker exec php bash -c "bin/phpstan analyse"

      - name: Run tests
        run: docker exec php bash -c "bin/codecept run"
